### ISSUE TITLE
[Problema Luna] Primer paso

### ISSUE THREAD

**Issue by Malguzt** [OIA-Resistencia/BolsaDeGatos#1]
Abrir el archivo luna.txt y hacer una copia de los tres párrafos unos renglones debajo del texto dado (¡no borrar el original!). Las modificaciones deberán ser realizadas en esta copia, dejando los tres párrafos originales intactos.

**Comment by DrJSimpson-zz** [comment]
Chicos, este es el primer issue que vamos a generar, vean las instrucciones, y si tienen problemas ya saben, whatsapp mail, o cualquier medio de comunicación.

**Comment by Malguzt** [comment]
XD me di cuenta que este es un problema de la categoría "Inicial", osea no es de programación, así que voy a borrar todo lo que subí al respecto.
